.gitignore, .travis.yml, README.md, config/config.yaml, config/prod/genie.yaml, hooks/notify_ec2.py, hooks/synapse_external_bucket.py, scripts/DeleteSynapseExternalBucket.sh, templates/SynapseExternalBucket.yaml, templates/genie.yaml, templates/managed-ec2-v2.yaml
* setup the same files for travis ci as scicomp-provisioner.
* move genie provisioned resource from sandbox-infra rep to this repo.
=> setup travis ci for provisioner

config/prod/neurolincs-unique-objects.yaml
Create an EC2 to process neurolincs images.
=> Create neurolincs unique objects ec2

config/prod/test-jumpcloudclientsetup.yaml
An instance for users to test JumpCloud setup.
=> Setup EC2 instance for testing connectivity after JC setup.

templates/genie.yaml
Add batch job definition for GENIE release
=> Add batch release process

config/prod/JKG-ec2-v5.yaml
new file:   config/prod/JKG-ec2-v5.yaml
=> Add EC2 Request

.travis.yml, .yamllint, config/prod/JKG-ec2-v5.yaml, config/prod/gene-drug-db-test-instance-ec2.yaml, config/prod/minidream-R-env-pub-instance-ec2.yaml, config/prod/minidream-R-env-test-instance-ec2.yaml, config/prod/mssm-transfer-bucket.yaml, config/prod/nf-osi-processing.yaml, config/prod/pmc-test-ec2.yaml, config/prod/test-jumpcloudclientsetup.yaml
It is difficult for humans to validate yaml syntax when reviewing
provisioner scripts. Setup yamllint[1] to automate validation of
yaml syntax on pull requests.
[1] https://github.com/adrienverge/yamllint
=> [IT-515] Setup yaml syntax checker

.travis.yml
Validate that the newly provisioned resource contains a unique
stack_name.
This depends on PR:
https://github.com/Sage-Bionetworks/infra-utils/pull/19
=> [IT-506] check for unique stack name

templates/genie.yaml
Remove out daily GENIE batch validation for now on sandbox.  In the process of updating scicomp.
=> Comment out daily submission on sandbox

config/prod/dgutman-htan-s3.yaml
correct ARN with /user for dagutman added
=> added correct dagutman ARN

config/prod/tom-test-window.yaml
Im curious in how to access this instance, and what this looks like.
=> Test window instance

config/prod/xschildw-wininst
Only changed name and contact.
=> xschildw_windows_instance

config/prod/toil-test-machine.yaml
Requires https://github.com/Sage-Bionetworks/aws-infra/pull/114
=> Use new template with increased timeout.

config/prod/tom-cvat.yaml
I need two ports open.  Is it possible by doing this?
=> Create cvat instance

config/prod/ahayden-test-awslinux.yaml
Testing a write up of the process. I'll tear it down later on.
=> testing deployment proc

config/prod/xdoan-test-s3.yaml
HTAN test upload/download file s3 bucket
=> s3 bucket for testing

config/prod/ubuntu-rstudio-ami.yaml
Requesting change of instance type to compute optimized (for processing large MAF files). Please warn me if this will wipe out all my data.
=> Changing instance type to compute optimized

config/prod/tom-analysis.yaml
=> Request instance - tom-analysis

config/prod/branch-name-bememea_test.yaml
=> bememea testing deployment

config/prod/ubuntu-rstudio-ami.yaml
Processing even larger files, so requesting a beefier instance to prevent RStudio from crashing. Please warn me if this will wipe out all the data currently on the instance.
=> Requesting change in instance type

config/prod/mmason-beefier-bioc.yaml
I changed the AMI ID to match what we wanted initially... hopefully this deploys successfully now.
=> update mmason beefier definition

config/prod/new-test-instance-for-minneker.yaml
This is a test deployment of a sandbox instance as described in the Sage AWS Provisioner.
=> minneker testing deployment

config/prod/tom-ncats.yaml
This instance is for routing traffic to the NCATS server.  Can you also give @tschaffter and @jaeddy access?
=> Add in ncats routing server

config/prod/xschildw-test-stack-tags.yaml
Quick test to see if spectre tagging the template works. Picked this old template as it does not have defaults on params (i.e. tags should come from tagging the template).
=> M test stack tags

.github/PULL_REQUEST_TEMPLATE.md
Setup a PR template[1] for people making PRs to request
resources. Hopefully it will help reduce the confusion around
templates and workflows.
[1] https://help.github.com/en/articles/about-issue-and-pull-request-templates#pull-request-templates
=> Setup a PR template

config/prod/ahayden-testhost-lin.yaml
=> Adding sandbox Linux testing host

config/prod/ahayden-testhost-win.yaml
=> Requesting Windows instance for testing

config/prod/ahayden-testhost-win.yaml
Previous AMI no longer available
=> Fixing AMI id

config/prod/mmason-beefier-bioc.yaml
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
yamllint.................................................................Passed
AWS CloudFormation Linter................................................Passed
Tabs remover.............................................................Passed
=> just switching instance types to beefier one

config/prod/mmason-beefier-bioc.yaml
pre-commit run --all-files
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
yamllint.................................................................Passed
AWS CloudFormation Linter................................................Passed
Tabs remover.............................................................Passed
=> requesting more compute

config/prod/ecmonsen-code-storage-s3.yaml
Create a bucket for storing built lambda code zip files.
=> add bucket for lambda code storage

config/prod/dwebster-sandbox-host.yaml
Requesting an instance to try out the provisioner. All ok?
=> Adding host for general sandboxing

config/prod/dwebster-sandbox-host.yaml
Wanting to use ubuntu for the package manager
=> close the ports and switch to ubuntu

config/prod/dgutman-htan-ec2.yaml, config/prod/xschildw-wininst.yaml
To make it easier for linters to parse
=> linting requires quotes around braces

config/prod/dgutman-htan-new2-ec2.yaml
Creating a new EC2 and then will delete the non-working EC2
=> new ec2 since the old one won't work after being stopped

config/prod/xschildw-packertest.yaml
Picked the latest packer-base-ubuntu AMI. This is to test the commands to setup multiple Rs and other deps.
=> Request an instance to test packer setup of ShinyPro AMI

config/prod/xschildw-packer-shinyserver-pro.yaml, config/prod/xschildw-packertest.yaml
xschildw is requesting an instance built from packer to figure out why the shiny package won't install in packer.
=> Packer-shinyserverpro-tst

config/prod/xschildw-shinyserverpro-test.yaml
Per review, this just adds an instance.
=> Add shinyserverpro test instance

config/prod/JKG-s3.yaml, config/prod/dgutman-htan-s3.yaml, config/prod/xdoan-clarisse-htan-s3.yaml, config/prod/xdoan-test-s3.yaml
Now that we only allow access to AWS thru jumpcloud we need to
update all the GrantAccess configuration in S3 Buckets to the
new assumed role ARN
=> [IT-922] Update GrantAccess config for S3 buckets

.pre-commit-config.yaml, .travis.yml
* Update pre-commit hooks
* Don't allow travis to auto update pre-commit hooks so that
it's consistant with local execution of `pre-commit run --all-files`
=> Update pre-commit hooks and turn off auto update

config/prod/dgutman-htan-ec2.yaml, config/prod/dgutman-htan-new2-ec2.yaml, config/prod/dgutman-htan-s3.yaml, config/prod/xdoan-clarisse-htan-s3.yaml, config/prod/xdoan-htan-ec2.yaml, config/prod/xdoan-test-s3.yaml
This change assigns ownership of sandbox resources for HTAN to Bruno per IT-1088
Passes pre-commit
@zaro0508 please confirm that bucket `SynapseUserName` changes are not destructive.
=> Change ownership of HTAN resources

config/prod/JKG-s3.yaml, config/prod/dgutman-htan-s3.yaml, config/prod/xdoan-clarisse-htan-s3.yaml, config/prod/xdoan-test-s3.yaml
We switched from SAML integration to SSO which uses a different role
for federated user access. We update with the new SSO role.
=> update resouce access for SSO

config/prod/dgutman-htan-new2-ec2.yaml, config/prod/dgutman-htan-s3.yaml
Our collaborator no longer needs access to these DSA resources in sandbox.
=> Limit access to DSA resources

config/prod/JKG-s3.yaml, config/prod/bgrande-nextflow-service-account.yaml, config/prod/dgutman-htan-new2-ec2.yaml, config/prod/dgutman-htan-s3.yaml, config/prod/minidream-R-env-pub-instance-ec2.yaml, config/prod/tom-ncats.yaml, config/prod/xdoan-clarisse-htan-s3.yaml, config/prod/xdoan-htan-ec2.yaml, config/prod/xdoan-test-s3.yaml
Add a [Sage CostCenter tag](https://github.com/Sage-Bionetworks/aws-infra/tree/master/templates/tags) to resources deployed by the sandbox
provisioner using [sceptre stack_tags](https://docs.sceptre-project.org/dev/docs/stack_config.html#stack-tags)
Also change sceptre configs to use sceptre [template handlers](https://docs.sceptre-project.org/dev/docs/template_handlers.html) instead of hooks
=> [IT-1552]  Apply CostCenter tags to resources

.pre-commit-config.yaml
Use Sceptre's sceptrelint[1] pre-commit linter to check
scptre stack configs for correctly defined templates
[1] https://github.com/Sceptre/sceptrelint
=> [IT-1531] Use pre-commit sceptrelint

config/prod/jharker-test.yaml
Add a test stack to learn how the process works
=> Learning exercise

config/prod/jharker-test.yaml
The ubuntu instance is failing to start or otherwise send the cnf signal.
=> Revert "Move jharker-test to an Ubuntu AMI"

config/prod/jharker-test.yaml
Give Joni access to the jharker-test instance
=> Update ssh keypair for jharker-test
