templates/managed-ec2-v4.yaml

The policy[1] that we use to integrate with ParkMyCloud[2]
requires a `parkmycloud=yes` tag to allow the service
to start and stop any resources on AWS.
[1] https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/ParkMyCloud.yaml#L74
[2] https://www.parkmycloud.com

[IT-433] tag for park my cloud

---

templates/managed-ec2-v2.yaml
templates/managed-ec2-v3.yaml
templates/managed-ec2-v4.yaml

New AWS cloudformation linter rules don't like `hi1.4xlarge`
and `cg1.4xlarge` instance types.  I'm not sure why but we
can remove them to satisfy the linter because we don't use them.

update template for new linter rules

---

templates/SynapseExternalBucket-v2.yaml

This is to setup cross account access[1].  Add a parameter to
allow the provisioner to specify which users can have access
to the provisioned bucket.  It is not a required parameter,
if nothing is specified no access will be given.
[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example2.html

Option to give users access to the provisioned bucket

---

config/prod/mssm-transfer-bucket.yaml

This is related to commit 335107f
Our collaborators at MSSM do not want to create an AWS account for
us to setup cross account access for them to access one of our buckets
so they can transfer files to Sage.
After further discussion with MSSM we've decided to provide MSSM
with an Sage IAM account user access key with access to the bucket.

create a bucket for MSSM to transfer files

---

templates/managed-ec2-v4.yaml

Users may want to run an application on the EC2 instance and open
a port to it so other can access the app from a client.  This
allows opening a port for incoming traffic to the EC2.
It is not a required parameter, if nothing is specified no ports
will be open.

[IT-489] Option to open a port to incoming traffic

---

templates/managed-ec2-v5.yaml

We only need to open port 22 when setting up an instance
that has a public IP address (public subnet).
All ports are open when the instance is in a private subnet
for users that are inside the sage VPN.

Fix open ssh port

---

.travis.yml

Some AWS resources, like cloudfront, can take a long time to deploy
without logging status to the console.  We increase travis_wait[1]
so the build won't timeout and fail.
[1] https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

Increase travis wait time

---

templates/managed-ec2-v6.yaml

Apply tags to root volume so that we can use the Data Lifecylce
Manager[1] to automatically backup EC2 instances.
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html

[IT-520] Apply tags to root volume

---

.yamllint

To help validate that there are no duplicatee stack_name in new PRs
we need to be ore strick with the yaml to provision resources.
This will flag colons spacing issues[1] as errors instead of warnings.
[1] https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons

[IT-506] flag colon spacing in yaml as errors

---

.travis.yml

a change to lint_stack.sh script no longer requires passing
in a parameter:
https://github.com/Sage-Bionetworks/infra-utils/commit/166075f275cac9b1c554cfc2b6a14ed38a6a4898

lint_stack.sh no longer requires a parameter

---

.travis.yml

Use lint_stack[1] to validate the following items for newly
provisioned stack name:
1. stack name contains valid characters.
2. stack name is not a duplicate of existing stack names.
[1] https://github.com/Sage-Bionetworks/infra-utils/blob/master/ci/lint_stack.sh
fde8f8f

[IT-506] lint newly provisioned stack name for errors

---

templates/managed-ec2-v6.yaml

Call a nested template to enable a daily EC2 backup using the Data
Lifecycle Manager[1].  Provisioners have the option to enable or
disable the backup.
[1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html

[IT-520] Provide option to backup EC2

---

config/config.yaml
templates/managed-ec2-v6.yaml

All provisioning using the new template
Sage-Bionetworks/aws-infra/templates/managed-ec2-v7.yaml
will need to set these params
```
template_path: remote/managed-ec2-v7.yaml
AMIId: {{stack_group_config.default_ami}}
KeyName: {{stack_group_config.default_key_pair}}
VpcName: {{stack_group_config.default_vpc}}
hooks:
before_create:
- !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v7.yaml --create-dirs -o templates/remote/managed-ec2-v7.yaml"
before_update:
- !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/managed-ec2-v7.yaml --create-dirs -o templates/remote/managed-ec2-v7.yaml"
after_create:
- !ec2_notify "{{stack_group_config.aws_account_name}} …
```

[IT-488] Use shared EC2 provisioner template

---

config/prod/dgutman-htan-s3.yaml

cloudformation reports that there is an invalid principal in s3 policy.
i suspect it's the dgutman ARN.
CF error message:
ExternalBucketPolicy AWS::S3::BucketPolicy CREATE_FAILED Invalid principal in policy
(Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy;
Request ID: E6C52D0405DF833C; S3 Extended Request
ID: 4NTE0nmra7HWcOO6CFUTw7KTw1rd5aIkhO00XPwxoLB3Uc6zKxPUU8pG//WeN+ZXg2q1XouJsrQ=)

remove invalid principal from s3 policy

---

config/prod/tom-test-ubuntu.yaml

This is failing on travis only, it works when deployed locally.  The
problem seems to be that it's using the aws linux template[1] instead
of the ubuntu template.  My guess is that travis is over aggressively
cacheing files therefore not replacing the aws linux template.
We attempt to fix by downloading to a different file.

Fix ubuntu deployment

---

config/prod/ubuntu-rstudio-ami.yaml

Requesting an ubuntu instance to run a publicly available Rstudio AMI (http://www.louisaslett.com/RStudio_AMI/) in US-East1 zone with increased instance size.
-Removed tabs/spaces causing earlier errors in PR
-OK with pre-inspection of the public AMI by sage IT team

Requesting Ubuntu RStudio AMI

---

config/prod/tom-cvat.yaml

A GPU is required for this application as it is a video annotator.   Without it, the video streams incredibly slow.
This is required for the prototype as we are having one user test its functionality.

Update to instance with GPU

---

config/prod/jb-new-instance-1.yaml

Adding new instance type to enable SSD and increased RAM. Use of at least 32MB RAM and SSD volume is recommended for running VCF2MAF analysis package.

Requesting change of instance type and volume to existing instance

---

config/prod/ubuntu-rstudio-ami.yaml

Requesting change of AMI to reflect current R (3.6) and RStudio (1.2) versions. Using US East AMI ID from http://www.louisaslett.com/RStudio_AMI/.

Changing instance AMI

---

config/prod/tom-test-ubuntu16.yaml

provisioner failed with message:
[2019-07-03 01:51:11] - prod/tom-test-ubuntu16 Ec2Instance AWS::EC2::Instance
CREATE_FAILED Volume of size 8GB is smaller than  snapshot
'snap-0a6548e5ad1936d4b', expect size >= 100GB (Service: AmazonEC2;
Status Code: 400; Error Code: InvalidBlockDeviceMapping;
Request ID: 401e3b5d-ce96-4f3c-8ca6-8c871a3b824a)
Attempt to fix instance

fix tom-est-ubuntu16 instance

---

config/prod/ubuntu-rstudio-ami.yaml

The memory intensive analysis is finished, so now changing the instance type back to general purpose to carry on analyses that are not super memory intensive.

changing instance type to general purpose instance

---

config/prod/nf-vcf-proc.yaml

The instance type for this stack was mistakenly changed by Sara. Changing it back to compute optimized for further VCF processing.

Changing instance type back to compute optimized

---

config/prod/ecmonsen-emorypipeline-lambda.yaml

The ecmonsen-emorypipeline-lambda-code[1] was previously being deployed
to a bucket in org-sagebase-sandbox account.  We have now changed it to
deploy to a bucket in org-sagebase-scicomp account.  Also a new version
was created.  Redirect references to the new bucket.
[1] https://github.com/Sage-Bionetworks/ecmonsen-emorypipeline-lambda-code

update references to ecmonsen lambda

---

config/prod/bgrande-nextflow-iam.yaml
config/prod/bgrande-nextflow-service-account.yaml

This service account will be used by Nextflow to store intermediate files in S3 while running a data processing workflow. I can't use my `sandbox-developer` role because the credentials expire in 8 hours whereas workflows can run for days. I'm going to test this setup using non-PHI data. If it works, I'll set up an equivalent service account in `scicomp`. 
This PR isn't based on a template, but it's inspired by the [stack](https://github.com/Sage-Bionetworks-IT/organizations-infra/blob/master/org-formation/600-access/_tasks.yaml#L77-L89) I deployed for the Nextflow provisioner CI. I'm using `wget` as per the recommendation made when I authored this [stack](https://github.com/Sage-Bionetworks-Workflows/aws-workflows-nextflow-infra/blob/prod/config/prod/s3-cfn-templates.yaml#L1-L9). 
---- …

Create service account for Nextflow S3 access

---

config/prod/JKG-s3.yaml
config/prod/bgrande-nextflow-service-account.yaml
config/prod/dgutman-htan-new2-ec2.yaml
config/prod/dgutman-htan-s3.yaml
config/prod/minidream-R-env-pub-instance-ec2.yaml
config/prod/tom-ncats.yaml
config/prod/xdoan-clarisse-htan-s3.yaml
config/prod/xdoan-htan-ec2.yaml
config/prod/xdoan-test-s3.yaml

Sceptre supports template handlers[1] to get remote templates so we no
longer need to use hooks.  Convert all hooks to template handler.
[1] https://docs.sceptre-project.org/dev/docs/template_handlers.html

Use sceptre template handlers

---

.pre-commit-config.yaml

Use the new precommit linter check-stack-tags[1] to validate that
the assigned CostCenter tags are valid.
[1] https://github.com/Sceptre/sceptrelint

[IT-1531] Use sceptrelint validate stack tags

---

config/prod/jharker-test.yaml

I had deployed the stack before adding my ssh key to jump cloud. Attempt to work around a missing ssh key on the instance by changing the underlying AMI.

Move jharker-test to an Ubuntu AMI
